### ISSUE TITLE
scala.reflect.internal.Symbols.Symbol#ownerChain is called too many times when compile aka-actor

### ISSUE THREAD

**Issue by cryptom-dev** [rorygraves/scalac_perf#37] opened 2018-01-20 15:59 UTC
we probably can make it a var and only update it when onwer changes, so that it won’t get re-computed every time.

In terms of performance test, I think this cannot be easily microbenchmarked but perf_tester (macro benchmark) would be a good choice.

**Comment by mkeskells** [comment] 2018-01-20 16:27
duplicate of https://github.com/rorygraves/scalac_perf/issues/3

**Comment by rorygraves** [comment] 2018-01-21 10:47
Closed as duplicate

**Closed as completed by rorygraves** 2018-01-21 10:47 UTC
